### ISSUE TITLE
DB: "created" timestamps should have timezones

### ISSUE THREAD

**Issue by richardsj** [lamassu/lamassu-scripts#47]
column type `timestamp` (which implies _without timezone_) should be `timestamptz` (i.e. _with timezone_) to allow the database to convert times automagically when running queries.

This used to be the case already in the 1.x schema.  Setting the timezone for results has to be done manually in postgresql.conf or in each DB connection session otherwise.

Most VMs/droplets start with a timezone that's not the same as the machine(s) geographic location.  Part of initial setup is therefore usually `dpkg-reconfigure tzdata` and that should ideally be all that's needed before using any DB client.

**Comment by joshmh** [comment]
@richardsj Yep, totally agree. This has been fixed in the latest db schema which is in the migrations directory of lamassu-server:

https://github.com/lamassu/lamassu-server/tree/https/migrations

This is a branch that's under heavy development now. It's a bit hard to see the full schema from those migrations, so here's a snapshot:

https://gist.github.com/joshmh/ea024ebc81839e0ade742d4c1365a370

And good point about default timezones. Might be easiest to default the server to UTC time. I'll look into putting that in the install script.

**Comment by richardsj** [comment]
Just put `dpkg-rexonfigure tzdata` into the script. It's interactive and
asks for continent etc, so would fit with the way the install script
queries for info such as login stuff

**Comment by naconner** [comment]
Included in v3:

```
       Column       |           Type           |                      Modifiers                       
--------------------+--------------------------+------------------------------------------------------
 created            | timestamp with time zone | not null default now()
 send_time          | timestamp with time zone | 
```

:+1:
